In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn.metrics

# Preparing Data

In [2]:
#importing data matrices
child_play_feat=np.genfromtxt('child_play_feat.txt',delimiter=' ')
dog_bark_feat=np.genfromtxt('dog_bark_feat.txt',delimiter=' ')
siren_feat=np.genfromtxt('siren_feat.txt',delimiter=' ')

#define inputs
X=np.vstack((child_play_feat,dog_bark_feat,siren_feat))

#define labels
yc=np.ones(child_play_feat.shape[0])
yd=np.ones(dog_bark_feat.shape[0])*2
ys=np.ones(siren_feat.shape[0])*3
y=np.hstack((yc,yd,ys))

In [3]:
#Splitting in training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [4]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# SVM Linear Kernel

In [5]:
#Training of SVM
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [6]:
#prediction of SVM
y_pred = svclassifier.predict(X_test)

In [7]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 4  6  2]
 [ 3 27  3]
 [ 2  0  1]]
              precision    recall  f1-score   support

         1.0       0.44      0.33      0.38        12
         2.0       0.82      0.82      0.82        33
         3.0       0.17      0.33      0.22         3

    accuracy                           0.67        48
   macro avg       0.48      0.49      0.47        48
weighted avg       0.68      0.67      0.67        48



# Gaussian Kernel

In [8]:
#Training of SVM with Gaussian Kernel
from sklearn.svm import SVC
svclassifier_gaussian = SVC(kernel='rbf',gamma='auto')
svclassifier_gaussian.fit(X_train, y_train)

#prediction of SVM
y_pred_gaussian = svclassifier_gaussian.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred_gaussian))
print(classification_report(y_test,y_pred_gaussian))

[[ 4  8  0]
 [ 4 29  0]
 [ 0  2  1]]
              precision    recall  f1-score   support

         1.0       0.50      0.33      0.40        12
         2.0       0.74      0.88      0.81        33
         3.0       1.00      0.33      0.50         3

    accuracy                           0.71        48
   macro avg       0.75      0.52      0.57        48
weighted avg       0.70      0.71      0.69        48



# K-nn with K=10

In [9]:
#Training
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(X_train, y_train)
#Prediction
y_pred_Knn = classifier.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_Knn))
print(classification_report(y_test, y_pred_Knn))

[[ 3  2  7]
 [12 14  7]
 [ 1  1  1]]
              precision    recall  f1-score   support

         1.0       0.19      0.25      0.21        12
         2.0       0.82      0.42      0.56        33
         3.0       0.07      0.33      0.11         3

    accuracy                           0.38        48
   macro avg       0.36      0.34      0.30        48
weighted avg       0.62      0.38      0.45        48



# Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
logreg_clf = LogisticRegression(solver='newton-cg',multi_class='auto')
logreg_clf.fit(X_train, y_train)
y_pred_Logistic=logreg_clf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_Logistic))
print(classification_report(y_test, y_pred_Logistic))

[[ 3  7  2]
 [ 3 27  3]
 [ 1  1  1]]
              precision    recall  f1-score   support

         1.0       0.43      0.25      0.32        12
         2.0       0.77      0.82      0.79        33
         3.0       0.17      0.33      0.22         3

    accuracy                           0.65        48
   macro avg       0.46      0.47      0.44        48
weighted avg       0.65      0.65      0.64        48



# Decision Tree

In [12]:
#Training
from sklearn.tree import DecisionTreeClassifier
classifier_dtree = DecisionTreeClassifier()
classifier_dtree.fit(X_train, y_train)
#Testing
y_pred_dtree = classifier_dtree.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_dtree))
print(classification_report(y_test, y_pred_dtree))

[[ 7  1  4]
 [10 20  3]
 [ 2  1  0]]
              precision    recall  f1-score   support

         1.0       0.37      0.58      0.45        12
         2.0       0.91      0.61      0.73        33
         3.0       0.00      0.00      0.00         3

    accuracy                           0.56        48
   macro avg       0.43      0.40      0.39        48
weighted avg       0.72      0.56      0.61        48



In [13]:
# #ROCAUC curve
# from sklearn.metrics import roc_auc_score
# sklearn.metrics.roc_auc_score(y_test,y_pred)